"""Active publishers, keyed by platform (BUILD_SPEC §7 distribution targets).

Targets: LinkedIn, Facebook, Instagram. (X is generated by tone() but not a
target here; YouTube needs a video asset — tracked as a follow-up, not wired.)
"""
from __future__ import annotations

from .base import Publisher
from .publishers import FacebookPublisher, InstagramPublisher, LinkedInPublisher

PUBLISHERS: dict[str, Publisher] = {
    "linkedin": LinkedInPublisher(),
    "facebook": FacebookPublisher(),
    "instagram": InstagramPublisher(),
}

# Platforms we actually distribute to (must have both a publisher AND a caption
# from tone()). These are the content rows the publish queue will pick up.
PUBLISH_TARGETS = ["linkedin", "facebook", "instagram"]
